// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "go-base/internal/logic/demo"
	_ "go-base/internal/logic/middleware"
	_ "go-base/internal/logic/user"
)
