// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-05-30 13:33:02
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Demo is the golang structure of table demo for DAO operations like Where/Data.
type Demo struct {
	g.Meta    `orm:"table:demo, do:true"`
	Id        interface{} //
	Fielda    interface{} //
	Fieldb    interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	DeletedAt *gtime.Time //
}
