// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2023-05-30 13:33:02
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Demo is the golang structure for table demo.
type Demo struct {
	Id        uint        `json:"id"        ` //
	Fielda    string      `json:"fielda"    ` //
	Fieldb    string      `json:"fieldb"    ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	DeletedAt *gtime.Time `json:"deletedAt" ` //
}
